<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Quassel Search</title>

    <meta name="viewport" content="user-scalable=no, initial-scale=1.0, maximum-scale=1.0, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="theme-color" content="#fff"/>
    <meta name="msapplication-navbutton-color" content="#fff">
    <meta name="apple-mobile-web-app-status-bar-style" content="#fff">

    <link rel="stylesheet" href="res/login.css">
    <link rel="stylesheet" href="res/material-icons.css">
</head>
<body>

<h1>Quassel Search</h1>
<h2>You have to login to access this page</h2>

<form method="post" action="login.php?action=login">
    <input name="username" type="text" placeholder="Username">
    <input name="password" type="password" placeholder="Password">
    <input type="submit" value="Login">
</form>

</body>
</html>
