<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Quassel Search</title>

    <link rel="stylesheet" href="res/login.css">
    <link rel="stylesheet" href="res/material-icons.css">
</head>
<body>

<h1>Quassel Search</h1>
<h2>You have to login to access this page</h2>

<form method="post" action="login.php?action=login">
    <input name="username" type="text" placeholder="Username">
    <input name="password" type="password" placeholder="Password">
    <input type="submit" value="Login">
</form>

</body>
</html>
