<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Quassel Search</title>

    <link rel="stylesheet" href="res/search.css">
    <link rel="stylesheet" href="res/material-icons.css">
</head>
<body>
<nav>
    <div class="wrapper">
        <div id="searchbar">
            <input name="q" id="q" placeholder="Search" type="text">
            <div id="searchicon" class="icon">search</div>
        </div>
    </div>
    <div id="actions">
        <a title="Logout" href="login.php?action=logout">
            <span class="icon">account_circle</span>
        </a>
    </div>
    <div id="autocomplete">
        <ul></ul>
    </div>
</nav>

<section id="results">
</section>

<div id="modal-background"></div>
<div id="bg"></div>

<script src="res/jquery.js"></script>
<script src="res/translations.js"></script>
<script src="res/sendercolor.js"></script>
<script src="res/search.js"></script>
</body>
</html>
