<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?php $t('title'); ?></title>

    <meta name="viewport" content="user-scalable=no, initial-scale=1.0, maximum-scale=1.0, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="theme-color" content="#4285f4"/>
    <meta name="msapplication-navbutton-color" content="#4285f4">
    <meta name="apple-mobile-web-app-status-bar-style" content="#4285f4">

    <link rel="icon" type="image/png" href="favicon.png">

    <link rel="stylesheet" href="res/search.css">
    <link rel="stylesheet" href="res/material-icons.css">
</head>
<body>
<nav>
    <div class="wrapper">
        <div id="searchbar">
            <input name="q" id="q" placeholder="<?php $t('search'); ?>" type="text" autocomplete="off">
            <div id="searchicon" class="icon">search</div>
        </div>
    </div>
    <div id="actions">
        <a title="<?php $t('logout'); ?>" href="login.php?action=logout">
            <span class="icon">account_circle</span>
        </a>
    </div>
    <div id="autocomplete">
        <ul></ul>
    </div>
</nav>

<section id="results">
</section>

<div id="modal-background"></div>
<div id="bg"></div>

<script src="res/jquery.js"></script>
<script>
    var translation = <?php echo json_encode($translation); ?>;
</script>
<script src="res/sendercolor.js"></script>
<script src="res/search.js"></script>
</body>
</html>
