<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?php $t('title'); ?></title>

    <link rel="shortcut icon" type="image/png" href="favicon.png">
    <link rel="shortcut icon" type="image/png" href="favicon.svg">
    
    <meta name="generator" content="Human v1.0">
    
    <meta name="referrer" content="origin">
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="HandheldFriendly" content="True">
    <meta name="apple-mobile-web-app-capable" content="yes">
    
    <meta name="viewport" content="user-scalable=no, initial-scale=1.0, maximum-scale=1.0, width=device-width">
    
    <meta name="theme-color" content="#0a70c0">
    <meta name="msapplication-navbutton-color" content="#0a70c0">
    <meta name="apple-mobile-web-app-status-bar-style" content="#0a70c0">

    <link rel="stylesheet" href="res/css/search.css">
</head>
<body>
<script src="res/js/util/storage.js"></script>
<script src="res/js/util/moment-with-locales.js"></script>
<script>
    function dateformatter(match, year, month, date, offset, string) {
        const dateFormat = Storage.exists('dateformat') ? Storage.get('dateformat') : 'L';
        return moment(new Date(year, month-1, date)).format(dateFormat).toString();
    }
    const translation = JSON.parse(JSON.stringify(<?php echo json_encode($translation); ?>).replace(/\%d\(([0-9]{4})-([0-9]{2})-([0-9]{2})\)/g, dateformatter));
</script>
<script src="res/js/util/nativejsx-prototypes.js"></script>
<script src="res/js/util/loader.js"></script>
<script src="res/js/util/component.js"></script>
<script src="res/js/util/mirccolorhandler.js"></script>
<script src="res/js/util/sendercolorhandler.js"></script>
<script src="res/js/util/statehandler.js"></script>

<script src="res/js/component/nohistoryelement.js"></script>
<script src="res/js/component/historyelement.js"></script>
<script src="res/js/component/history.js"></script>
<script src="res/js/component/nav.js"></script>
<script src="res/js/component/message.js"></script>
<script src="res/js/component/loadmore.js"></script>
<script src="res/js/component/error.js"></script>
<script src="res/js/component/loading.js"></script>
<script src="res/js/component/context.js"></script>
<script src="res/js/component/buffer.js"></script>
<script src="res/js/component/app.js"></script>
</body>
</html>
